version: '3'
services:
    front-management-service:
        restart: always
        build:
            context: ./front-management-service
        ports:
            - '3000:80'
        environment:
            - PRODUCT_MGMT_URL=http://product-management-service:8100

    eureka:
        build:
            context: ./myshop-eureka-server
        ports:
            - '8761:8761'

    config-server:
        depends_on:
            - eureka
        build:
            context: ./myshop-config-server
        volumes:
            - /config-repo:/repo
        ports:
            - '8888:8888'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka

    zuul:
        depends_on:
            - eureka
        build:
            context: ./myshop-zuul-server
        ports:
            - '8765:8765'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka

    product-management-service:
        depends_on:
            - eureka
        build:
            context: ./product-management-service
        ports:
            - '8100:8100'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
            - CLOUD_CONFIG_ADDRESS=http://config-server:8888
            - FRONT_MGMT_URL=http://192.168.99.101:3000
            