version: '3'
services:
    front-management-service:
        restart: always
        build:
            context: ./front-management-service
        ports:
            - '3000:80'
        environment:
            - PRODUCT_MGMT_URL=http://product-management-service:8100
    eureka:
        build:
            context: ./myshop-eureka-server
        ports:
            - '8761:8761'
    product-management-service:
        links:
            - eureka
        build:
            context: ./product-management-service
        ports:
            - '8100:8100'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka