version: '3'
services:
    front-management-service:
        restart: always
        build:
            context: ./front-management-service
        ports:
            - '3000:80'
        environment:
            - PRODUCT_MGMT_URL=http://product-management-service:8100
    eureka:
        build:
            context: ./myshop-eureka-server
        ports:
            - '8761:8761'
    config-server:
        build:
            context: ./myshop-config-server
        ports:
            - '8888:8888'
    zuul:
        build:
            context: ./myshop-zuul-server
        ports:
            - '8765:8765'
        environment:
            - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
            - FRONT_MGMT_URL=http://front-management-service:3000
    product-management-service:
        links:
            - eureka
        build:
            context: ./product-management-service
        ports:
            - '8100:8100'
        environment:
            - EUREKA_SERVER_ADDRESS=http://config-server:8888
            - CONFIG_SERVER_ADDRESS=
            - FRONT_MGMT_URL=http://front-management-service:3000
            