spring:
  application:
    name: myshop-zuul-server
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
frontManagement:
  url: ${FRONT_MGMT_URL:http://192.168.99.101:3000}