spring:
  application:
    name: myshop-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///./repo
server:
  port: 8888

#spring.security.user.name=root
#spring.security.user.password=secret

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}